version: "3.9"

services:
    astrometrynet:
        build: .
        image: astrometrynet/astrometrynet:0.85
        container_name: astrometrynet
        restart: always
        volumes:
            # INDEX DATA
            # local (less indexes, more speed)
            - /home/osservatorio/astrometry.net/data-local:/data1/INDEXES
            # nas (more indexes, less speed)
            #- /media/nascdf/Platesolver/data:/data1/INDEXES
            # SUBMISSIONS DATA
            - /media/nascdf/Platesolver/submissions_data:/src/astrometry/net/data
        network_mode: "host"
